# DESCRIPTION: Github actions config
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

name: Contributor Agreement

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Test:
    name: "'docs/CONTRIBUTORS' was signed"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: test_regress/t/t_dist_contributors.pl
