---
# DESCRIPTION: Github actions config
# This name is key to badges in README.rst, so we use the name build
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

name: RTLMeter PR results

on:
  workflow_run:
    workflows:
      - RTLMeter
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read
      pull-requests: write
    steps:
      - name: Download report
        uses: actions/github-script@v7
        with:
          name: rtlmeter-pr-results
          run-id: ${{ github.event.workflow_run.id }}
          github-tokne: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -la
          cat report.txt
          gh pr --repo ${{ github.repository }} comment ${{ github.event.workflow_run.pull_requests[0].number }} --body-file report.txt
